export class HandTracker {
  constructor({ detector = null, onLandmarks, onStatus, targetFps = 15 } = {}) { this.detector = detector; this.onLandmarks = onLandmarks; this.onStatus = onStatus; this.targetFps = Math.max(8, Math.min(20, targetFps)); this.video = null; this.running = false; this.inference = false; this.frameHandle = null; this.lastInference = 0; this.inferenceCount = 0; this.skippedFrames = 0; this.lastDuration = 0; }
  async initialize() { if (this.detector) return true; this.onStatus?.({ state: "unavailable", message: "Local hand landmark model is not installed." }); return false; }
  async start(video) { if (!(await this.initialize())) return false; this.stop(); this.video = video; this.running = true; this.onStatus?.({ state: "searching" }); this.schedule(); return true; }
  schedule() { if (!this.running || !this.video) return; const callback = timestamp => { this.frameHandle = null; this.tick(timestamp); }; if (typeof this.video.requestVideoFrameCallback === "function") this.frameHandle = this.video.requestVideoFrameCallback(callback); else this.frameHandle = requestAnimationFrame(callback); }
  async tick(timestamp = performance.now()) { if (!this.running) return; const interval = 1000 / this.targetFps; if (timestamp - this.lastInference < interval) { this.skippedFrames += 1; this.schedule(); return; } if (this.inference) { this.skippedFrames += 1; this.schedule(); return; } this.inference = true; this.lastInference = timestamp; const started = performance.now(); try { const result = await this.detector.detectForVideo(this.video, timestamp); this.inferenceCount += 1; this.onLandmarks?.(result, timestamp); } catch (error) { this.onStatus?.({ state: "error", message: error.message || "Hand tracking failed", error }); } finally { this.lastDuration = performance.now() - started; this.inference = false; this.schedule(); } }
  stop() { this.running = false; if (this.frameHandle !== null) { if (typeof this.video?.cancelVideoFrameCallback === "function") this.video.cancelVideoFrameCallback(this.frameHandle); else cancelAnimationFrame(this.frameHandle); } this.frameHandle = null; this.video = null; this.inference = false; this.onStatus?.({ state: "stopped" }); }
  diagnostics() { return { running: this.running, inferenceFps: this.inferenceCount, inferenceMs: this.lastDuration, skippedFrames: this.skippedFrames, modelAvailable: Boolean(this.detector) }; }
}
