import { landmarkPoint, pinchPoint, GuidePointFilter } from "./guide-point.js";
import { createContourTarget, nearestContourPoint, videoToStage } from "./trace-guide-math.js";
import { estimateToolPoint, normalizeToolCalibration } from "./tool-calibration.js";
import { GUIDE_TOLERANCES, normalizeGuideState, updateGuideProgress } from "./trace-guide-state.js";

export class TraceGuideController {
  constructor({ video, stage, tracker = null, renderer = null, onUpdate, onStatus } = {}) { this.video = video; this.stage = stage; this.tracker = tracker; this.renderer = renderer; this.onUpdate = onUpdate; this.onStatus = onStatus; this.state = normalizeGuideState(); this.filter = new GuidePointFilter(); this.target = null; this.calibration = null; this.enabled = false; this.lastRaw = null; }
  setContour(points = [], options = {}) { this.target = createContourTarget(points, options); this.state.contourId = options.id || this.state.contourId; this.state.progressIndex = 0; this.state.progress = 0; this.state.highestProgress = 0; this.emit(); }
  setSettings(settings = {}) { this.state = normalizeGuideState({ ...this.state, ...settings }); this.filter.smoothing = this.state.smoothing; this.emit(); }
  setCalibration(calibration) { this.calibration = normalizeToolCalibration(calibration); }
  async enable() { this.enabled = true; this.state.enabled = true; if (!this.tracker) { this.onStatus?.({ state: "unavailable", message: "Trace Guide hand tracking is unavailable." }); this.state.status = "Unavailable"; this.emit(); return false; } const started = await this.tracker.start(this.video); if (!started) { this.state.status = "Unavailable"; this.emit(); return false; } this.state.status = "Searching"; this.emit(); return true; }
  disable() { this.enabled = false; this.state.enabled = false; this.state.running = false; this.tracker?.stop(); this.filter.reset(); this.renderer?.clear(); this.emit(); }
  pause() { this.state.running = false; this.state.status = "Paused"; this.emit(); }
  resume() { if (this.enabled) { this.state.running = true; this.state.status = "Searching"; this.emit(); } }
  handleLandmarks(result, timestamp = performance.now()) { if (!this.enabled || !result || (!this.state.running && this.state.status !== "Tracking lost")) return; const landmarks = result.landmarks?.[0] || result; const confidence = Number(result.handednesses?.[0]?.[0]?.score ?? result.confidence ?? .7); let anchor = landmarkPoint(landmarks, 8); if (this.state.mode === "pinch") { const pinch = pinchPoint(landmarks); if (!pinch?.active) { this.state.status = "Paused"; this.emit(); return; } anchor = pinch.point; } if (this.state.mode === "tool") anchor = estimateToolPoint(anchor, this.calibration); if (!anchor) { this.state.status = "Tracking lost"; this.emit(); return; } const dimensions = { videoWidth: this.video?.videoWidth, videoHeight: this.video?.videoHeight, stageWidth: this.stage?.clientWidth, stageHeight: this.stage?.clientHeight, mirrored: Boolean(this.video?.classList?.contains("selfie-camera")), fit: "cover" }; const mapped = videoToStage(anchor, dimensions); if (!mapped) return; const filtered = this.filter.update(mapped, timestamp, confidence); const guidePoint = filtered.predicted || filtered.stabilized; this.lastRaw = mapped; const targetPoint = this.target ? nearestContourPoint(this.target, guidePoint, { progressIndex: this.state.progressIndex, searchRadius: Math.max(8, (GUIDE_TOLERANCES[this.state.tolerance] || 22) * 2), direction: this.state.direction, allowGlobal: this.state.status === "Tracking lost" || this.state.progress === 0 }) : null; this.state = targetPoint ? updateGuideProgress(this.state, targetPoint, this.target, { confidence, acquisitionRadius: GUIDE_TOLERANCES[this.state.tolerance] }) : normalizeGuideState({ ...this.state, confidence, status: "Acquiring" }); this.state.guidePoint = guidePoint; this.state.rawGuidePoint = mapped; this.state.targetPoint = targetPoint?.point || null; this.state.lookAheadPoint = this.target?.points?.[Math.min(this.target.points.length - 1, (targetPoint?.index || 0) + this.state.direction * 10)] || null; this.state.deviation = targetPoint?.distance ?? null; this.renderer?.render(this.state); this.onUpdate?.(this.state); }
  diagnostics() { return { ...this.tracker?.diagnostics?.(), enabled: this.enabled, targetPoints: this.target?.points?.length || 0, progress: this.state.progress, deviation: this.state.deviation, status: this.state.status }; }
  emit() { this.onUpdate?.(this.state); this.renderer?.render(this.state); }
}
