import assert from "node:assert/strict";
import { createLayer, duplicateLayer, cloneLayers } from "../layers.js";

const first = createLayer({ image: "data:image/png;base64,one", name: "Sketch" });
assert.equal(first.visible, true);
assert.equal(first.opacity, .55);
const copy = duplicateLayer(first);
assert.notEqual(copy.id, first.id);
assert.equal(copy.name, "Sketch copy");
const cloned = cloneLayers([first, copy]);
assert.equal(cloned.length, 2);
assert.notEqual(cloned[0], first);
const nested = createLayer({ image: "data:image/png;base64,nested", trace: { enabled: true, mode: "Clean Lines", settings: { strength: .4 }, contourProgress: { a: "done" } }, perspective: { quad: [{ x: 0, y: 0 }] } });
const nestedClone = cloneLayers([nested])[0];
nestedClone.trace.settings.strength = .9;
nestedClone.trace.contourProgress.a = "skipped";
nestedClone.perspective.quad[0].x = 1;
assert.equal(nested.trace.settings.strength, .4);
assert.equal(nested.trace.contourProgress.a, "done");
assert.equal(nested.perspective.quad[0].x, 0);
const masked = createLayer({ image: "data:image/png;base64,masked", trace: { settings: { mask: { version: 1, strokes: [{ mode: "ignore", radius: 8, points: [{ x: .2, y: .3 }] }] } } } });
const maskedClone = cloneLayers([masked])[0]; maskedClone.trace.settings.mask.strokes[0].points[0].x = .9;
assert.equal(masked.trace.settings.mask.strokes[0].points[0].x, .2);
console.log("layer model tests passed");
